model_config:
  model_store:
    pretrained_model_path: ./models
    force_upload: false
    s3_prefix: models/diffusion-models/
    model_version: sdxl-turbo
  model_name: sdxl-turbo
inference_config:
  batch_size: 1
  height: 512
  width: 512
  num_steps: 50
style_prompt_config:
  styles:
  - van gogh
  - salvador dali
  - warhol
  - Art Nouveau
  - Ansel Adams
  - basquiat
  subjects:
  - mahatma gandhi
  - dalai lama
  - alan turing
  num_images: 10
seed: 42
