video:
  model_config:
    model_store:
      pretrained_model_path: ./video-models
      force_upload: false
      s3_prefix: models/diffusion-models/
      model_version: stable-video-diffusion-img2vid
    model_name: stable-video-diffusion-img2vid
  inference_config:
    # Numbers provided here are for Tesla V100 16GB GPUs. Adjust accordingly.
    frame_rate: 7 # Affects GPU VRAM usage
    decoding_timesteps: 1 # Affects GPU VRAM usage
    num_steps: 25
    num_frames: 20 # Affects GPU VRAM usage
    motion_bucket_id: 150
    low_vram_mode: true # Affects GPU VRAM usage
    resize: true # Affects GPU VRAM usage
  seed: 12232
image:
  model_config:
    model_store:
      pretrained_model_path: ./models
      force_upload: false
      s3_prefix: models/diffusion-models/
      model_version: stable-diffusion-xl-base-1.0.1
    model_name: stable-diffusion-xl-base-1.0.1
  inference_config:
    batch_size: 2
    height: 576
    width: 1024
    num_steps: 25
  prompt_config:
    prompts_cross_product:
      subjects:
      - A fawn Pembroke Welsh Corgi
      - A panda wearing sunglasses
      - A cute raccoon in a light blue suit
      - An origami brown bear
      actions:
      - skateboarding
      # - dancing energetically
      # - playing and strumming guitar
      locations:
      - in Bondi Beach
      # - in the sky
      # - in Times Square
      styles:
      - in photorealistic style
      - in Anime Manga style
      - in cubist painting style
    num_images: 1
  seed: 21412