video:
  model_config:
    model_store:
      pretrained_model_path: ./video-models
      force_upload: false
      s3_prefix: models/diffusion-models/
      model_version: stable-video-diffusion-img2vid
    model_name: stable-video-diffusion-img2vid
  inference_config:
    # Numbers provided here are for Tesla V100 16GB GPUs. Adjust accordingly.
    frame_rate: 7 # Affects GPU VRAM usage
    decoding_timesteps: 1 # Affects GPU VRAM usage
    num_steps: 25
    num_frames: 20 # Affects GPU VRAM usage
    low_vram_mode: true # Affects GPU VRAM usage
    resize: true # Affects GPU VRAM usage
    motion_bucket:
      bucket_id: 127
      sample_multiple_buckets: false # Setting This to TRUE will results in `num_motion_buckets_to_sample` video created from different samples of motion buckets
      num_motion_buckets_to_sample: 20
      motion_bucket_range: [0, 255]
  seed: 12232
image:
  model_config:
    model_store:
      pretrained_model_path: ./models
      force_upload: false
      s3_prefix: models/diffusion-models/
      model_version: sdxl-turbo
    model_name: sdxl-turbo
  inference_config:
    batch_size: 2
    height: 576
    width: 1024
    num_steps: 25
  prompt_config:
    prompts:
    - epic landscape where a colossal dragon looms out of the stormy sky, with huge red flames comes up of its mouth.
      Its scales are armored plates of ancient design, and its mane of sharp spines crests magnificently along its neck.
      At the mountain pass below, a lone figure carrying sword cloaked in a flowing robe stands resilient, facing the beast.
      The silhouette of the figure is backlit by a sliver of light piercing the horizon, which casts an ethereal glow over the
      rugged terrain. The dragon's breath swirls around it, mingling with the clouds, as the ground is littered with jagged rocks.
      This scene is a clash of legends, a moment captured in the timeless dance of human versus myth.
    num_images: 8
  seed: 21412
