video:
  model_config:
    model_store:
      pretrained_model_path: ./video-models
      force_upload: false
      s3_prefix: models/diffusion-models/
      model_version: stable-video-diffusion-img2vid
    model_name: stable-video-diffusion-img2vid
  inference_config:
    # Numbers provided here are for Tesla V100 16GB GPUs. Adjust accordingly.
    frame_rate: 3 # Affects GPU VRAM usage
    decoding_timesteps: 1 # Affects GPU VRAM usage
    num_steps: 25
    num_frames: 20 # Affects GPU VRAM usage
    motion_bucket_id: 125
    low_vram_mode: true # Affects GPU VRAM usage
  seed: 422
image:
  model_config:
    model_store:
      pretrained_model_path: ./models
      force_upload: false
      s3_prefix: models/diffusion-models/
      model_version: stable-diffusion-xl-base-1.0.1
    model_name: stable-diffusion-xl-base-1.0.1
  inference_config:
    batch_size: 2
    height: 512
    width: 768
    num_steps: 25
  prompt_config:
    prompts:
    - Astronaut in on the amazon jungle petting a tiger, 8k very detailed and realistic,
      cinematic lighting, highly detailed, digital painting, artstation, concept art,
      smooth, sharp focus, illustration
    num_images: 4
  seed: 422
